version: '3.8'

services:
  # Service for the Spring Boot application
  tpachat-backend:
    image: houssemeddine40/tpachatproject-app:latest  # Use the Docker Hub image
    ports:
      - "8089:8089"  # Expose port 8089 for the application
    depends_on:
      - mysql-db  # Ensure MySQL starts before the backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tpachato?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword  # Change as necessary

  # Service for the MySQL database
  mysql-db:
    image: mysql:5.7  # Use MySQL 5.7 or another compatible version
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the MySQL root password
      MYSQL_DATABASE: tpachato  # Name of the database
    ports:
      - "3306:3306"  # Expose port 3306 for local access if necessary
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data

volumes:
  mysql_data:  # Define a volume for MySQL data persistence
