version: '3.8'

services:
  # Service pour l'application Spring Boot
  tpachat-backend:
    image: houssemeddine40/tpachatproject-app:33  # Use the pushed image
    ports:
      - "8089:8082"  # Expose port 8082 for the application (mapped to host port 8089)
    depends_on:
      - mysql-db  # Ensure that MySQL starts before the backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tpachato?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword

  # Service pour la base de données MySQL
  mysql-db:
    image: mysql:5.7  # Use MySQL 5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set MySQL root password
      MYSQL_DATABASE: tpachato  # Database name
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data

volumes:
  mysql_data:
